### ISSUE TITLE
DobleClick() not releasing the control if doubleClick() on a TreeNode gives a warning message.

### ISSUE THREAD

**Issue by rajkamaa** [TestStack/White#112]
HI,

When I'm trying to View the Tree Node, It is throwing error message...How we can handle it.

When I doubleClick() on a TreeNode, I'm expecting a new window but sometimes it gives a warning message "Error - Exit, restart or continue the program?" with Exit, Restart or Ignore button.

When It got this warning " ucrTreeNodeTemp1.DoubleClick();" it never release the control until I manually click any of the button.

Please help... Its very urgent for me.

My code below.
ucrTreeNodeTemp1 = ucrCommanderWindow.Get<White.Core.UIItems.TreeItems.TreeNode>(SearchCriteria.ByText(counterpartName + " (" + counterpartID + ")"));

// ucrTreeNodeTemp1.Expand();

ucrTreeNodeTemp1.DoubleClick();

var newWindow = ucrCommanderWindow.ModalWindow("Error - Exit, restart or continue the program?");

Thanks,
RajKamaa

**Comment by kfrajtak** [comment]
I do realize this issue has been closed, but would like to know how @rajkamaa was able to deal with it. Also I'd like to know how White deals with it, because I believe the problem described is a "feature" of the UIA and the access to application through UIA is blocked until (in this case Click event) has finished. And in the meantime the app will hang in White code. I have also run into this - see this [StackOverflow question](https://stackoverflow.com/questions/53881108/windows-automaton-invokepattern-blocking-execution-until-everything-has-comple).

Thanks for your reply,
Kare;
