### ISSUE TITLE
how to get control's native property

### ISSUE THREAD

**Issue by iquicktest** [TestStack/White#118]
I want get a control's property of backcolor, please tell me how to do that? Thanks

**Comment by korulis** [comment]
Hi,
this:
`control.VisibleImage.GetPixel(10, 10)
`
does not work. Because VisibleImage always has the size 1x1
I have code: 
`                var button = customerCollectOrderView.Get<Button>(SearchCriteria.ByText("1"));
                var h = button.VisibleImage.Height / 4;
                var w = button.VisibleImage.Width / 4;
                var color = button.VisibleImage.GetPixel(w, h);`

The button is found successfully. As you can see I am trying to determine the color by the first quarter of the button. The actual button is approximately 50x90 px. For the reason I mentioned above w and h always resolve to 0 and 0 respectively, instead of 12 and 22 respectively. 

![visibleimage](https://cloud.githubusercontent.com/assets/5428098/18515851/75337102-7a9f-11e6-88fd-666c45725481.png)
