### ISSUE TITLE
Couldn't find window with title

### ISSUE THREAD

**Issue by StanislauMinsk** [TestStack/White#151]
Hello, I use your lib, but 1 have problem into this method

public Window GetWindow(string title)
        {
            return this.host.GetWindow(title, InitializeOption.NoCache);
        }

I get error "Couldn't find window with title ***\* in process 3752, after waiting for 5000 ms", please help me. Thank you.

**Comment by ShorePhani** [comment]
Hi @JakeGinnivan, 
Above issue is valid, as I could reproduce when I put Window Forms --> Text property as kept as title of the window. whats wrong with that approach. Briefly explain windows form's title maps to exactly which property? thanks

**Comment by ShorePhani** [comment]
I see lack of documentation, Site is redirecting teststack.net but with weird text with no documenation, could you please redirect better sources of documentation for White features.

**Comment by SanmugaNathan** [comment]
An exception of type 'TestStack.White.AutomationException' occurred in TestStack.White.dll but was not handled in user code

Additional information: Couldn't find window with SearchCriteria Name=LoginWindow in process 10520, after waiting for 5000 ms

I am getting the above exception and the issue is valid. I have given everything right. Please help and correct me If I am wrong
