### ISSUE TITLE
Why cant I do window.Get<Tab> even though its an UIItem?

### ISSUE THREAD

**Issue by bpp9614** [TestStack/White#298]
I want to navigate to a particular Tab with name "myTab". I should be able to do this...
Tab tab = Window.Get<Tab>("myTab");

Why cannot I do this? 

![tab](https://cloud.githubusercontent.com/assets/12203604/7437579/c1c5a604-f015-11e4-9cca-b80c181acfc0.png)

**Comment by maxinfet** [comment]
In your example what is no window?

I just made a test application using the WpfTestApplication and I was able to use a tab control fine. If you post more code I might be able to give a more specific answer. Here is the code I used to test a tab control using the WpfTestApplication in TestStack.White.TestApps.WpfTestApplication.

    using System.Windows;
    using TestStack.White.UIItems.TabItems;
    using Application = TestStack.White.Application;

    namespace MyTestApp
    {
        public partial class MyTestWindow : Window
        {
            public MyTestWindow()
            {
                InitializeComponent();
            }

            private void Button_Click(object sender, RoutedEventArgs e)
            {
                Application application = Application.Attach("WpfTestApplication");
                var window = application.GetWindow("MainWindow");

                var tabControl = window.Get<Tab>("ControlsTab");
                tabControl.SelectTabPage("Input Controls");
            }
        }
    }

**Comment by jakobojvind** [comment]
You have probably not included the using clause `using TestStack.White.UIItems.TabItems;`
Including this should give you the option to use code completion for getting `Tab`.

**Comment by bpp9614** [comment]
Jako- you are correct !! using clause was missing. I dont have to include anything namespace for buttons, but why for Tab?

**Comment by jakobojvind** [comment]
@bpp9614 - `Tab` is placed in the namespace `TestStack.White.UIItems.TabItems` and `Button` in the namespace `TestStack.White.UIItems`. I could say, that's just how it's designed, but I think the reason for why placing the `Tab` in a separate namespace is caused by the fact that a Tab control consist of several objects. The Tab it self is the container for `TabPages` which is a collection of `TabPage`.
`Button` only consist of a single object, why it can be placed in the main namespace for UIItems.
