### ISSUE TITLE
Some Questions About TestStack White

### ISSUE THREAD

**Issue by exigez** [TestStack/White#324]
Hi,
I am looking into several possible solution to create infrastructure for Automation Testing for my team and came across TestStack White. Trying to understand if I can utilize it. If you could answer the below I’d be grateful. 
Bellow I will refer to a string of action the need to be automated as a ‘flow’.
Basically, I need the following to be possible:
1.	Starting a flow on one computer and completing it on a different computer.
2.	Being able to identify and manipulate Java, WPF, QT and windows UI elements.
3.	Run executables in the command line
4.	Access the file system
5.	Work on Windows 2008, windows 7, windows 10. Maybe mac as well.
6.	Measure the time an action takes.
7.	Read and write into files

Thanks for your help.

**Comment by JakeGinnivan** [comment]
White’s responsibility would be 2 and 5. But it is hosted in tests so you could write code to do the other things. It will not run on Mac though.

**Comment by dpisanu** [comment]
Aloha,
let me just add to Jake's answer there. :)

1. Since TestStack.White runs inside the scope of the Test you would need to split your test into PartA and PartB where each part runs on a different machine. This is the only way if you want to spread a workflow across different machines. 
PartA works on MachineA, once done will need to start of notify a service on MachineB that will run PartB.
2. Before you start rolling out TestStack.White for your Tests, make sure the UIs you want to Automate are automatable. Being able to identify and manipulate Java, WPF, QT and windows UI elements. Use "UIAVerify" to see if the UI is accessible to the extend that you can go through your workflows. 
3. Your Test would start Executables. Simple Process.Start(). This is not a TestStack.White domain todo.
4. Here again you would use your .NET Framework toolset to access the Filesystem. This is not a TestStack.White domain todo.
5. Windows is supported. Mac is a nogo unless you are running Bootcamp on the mac and/or your Tests are hosted in a Windows instance. Oarakkeks Desktop and VMWare Fusion do offer a sort of seemless integration of Windows Programs into OSX. I doubt that TestStack.White, if run in such a scenario, will be able to cross the Windows hosted boundary over to the OSX world.
6. Use your .NET Framework tools to measure time. Not something that is in the TestStack.White domain todo.
7. See Point 4.

Hope we were able to clear up some questions there for you.
