### ISSUE TITLE
TestStack.White and a mock framework - is there a way?

### ISSUE THREAD

**Issue by revyrev** [TestStack/White#340]
Hello,

I wish to use this framework for automation of windows forms UI testing, but I need to mock some database and webservices related methods. Is there a way to do this with White? (since all you do is give it a path to an already compiled exe). How would I go about it? 

Any help is appreciated, cheers.

**Comment by eriviere** [comment]
White doesn't provide any mocking feature, but you can add an external library like Moq into your test solution:
https://github.com/Moq/moq4/wiki/Quickstart

**Comment by dpisanu** [comment]
TestStack.White does not include any mocking framework.
Since it runs also in a different process then your UI, mocking would be difficult. 

Depending how your project is build up, you could do Component Tests where you run your UI control in a hosting window and mock the underlaying Data Content. (Using MVVM pattern).

If you want to go with TestStack.White you would need to create a Dummy Backend that allows connections and generated random data for your UI Program to work.

**Comment by revyrev** [comment]
That's what I suspected. Thanks for the responses!
