### ISSUE TITLE
Waiting on a property

### ISSUE THREAD

**Issue by kappa10j** [TestStack/White#400]
Is there a WaitProperty or any other kind of built in wait mechanism on a property value?

**Comment by ivan-danilov** [comment]
This code waits until some combobox gets item with certain text for 5 seconds. `loaded` shows afterwards whether waiting finished because of timeout (`false`) or because item was found (`true`):
`var loaded = Retry.For(() => ProjectCombobox.Items.Exists(item => item.Text == id), TimeSpan.FromSeconds(5));`

You can use similar approach for whatever you need to check with your properties. Or anything else on that matter ;)

**Comment by kappa10j** [comment]
thanks for the feedback.  very helpful
