### ISSUE TITLE
How to get a 'border' using TestStack.White

### ISSUE THREAD

**Issue by EyalShlomi** [TestStack/White#518]
Hi All,

I have being using TestStack.White for several days now, and now I'm stuck on something.
How to get a 'border' using TestStack.White?

e.g.: for a button I do:
TestStack.White.UIItems.Button button = win.Get<TestStack.White.UIItems.Button>(SearchCriteria.ByAutomationId(AutoId));

what is the equivalent for a 'border'?

I have an automatioId for it but how do I 'attach' to it?
I tried:
TestStack.White.UIItems.UIItem[] _lt = AutomationPOCWindow.GetMultiple<TestStack.White.UIItems.UIItem>(SearchCriteria.All);
I got Buttons, textBoxes, lables but no borders...

Thanks in advance!
Eyal 

![capture](https://cloud.githubusercontent.com/assets/24458517/21775161/e4cb44f8-d649-11e6-9b44-430e35dd8e75.png)

**Comment by Roemer** [comment]
You are looking at it with a WPF tool which shows WPF objects. White works with UIA objects so you need Inspect or FlaUInspect or UIAVerify to find the items. You should find it there as a Pane object.

**Comment by EyalShlomi** [comment]
hi.

in the inspect i do no see those items (no borders or grid)...

![capture2](https://cloud.githubusercontent.com/assets/24458517/21777814/6dcd7db0-d655-11e6-93e3-56722be9fea3.png)

**Comment by Roemer** [comment]
Then you can't get it except you write your own automationpeer which provides the border element to UIA. What do you need the border for anyway? Since you cannot interact with it it doesn't really make sense to have it in UIA.

**Comment by EyalShlomi** [comment]
The SW team uses the border as a Error marker for the user (illegal values triggers the border to become red).

**Comment by dpisanu** [comment]
I see what you are trying to check.
You are running into a dead end here.
Color Checks via White/UIA are horrible.
You are better left off writing a VisualTreeInspector extention for your
test setup that takes an UIA object and walks along the visual tree.
Then it's as easy as using snoop to check for values.
It's very unreliable from my past experience.

Am 10.01.2017 08:30 schrieb "EyalShlomi" <notifications@github.com>:

The SW team uses the border as a Error marker for the user (illegal values
triggers the border to become red).

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/TestStack/White/issues/518#issuecomment-271505433>, or mute
the thread

**Comment by EyalShlomi** [comment]
OK,
and how do I do it? (writing the  VisualTreeInspector ?)

**Comment by Roemer** [comment]
VisualTree is not part of White. Ask that in stackoverflow.
