### ISSUE TITLE
HRESULT: 0x80131040 - The located assembly's manifest definition does not match the assembly reference.

### ISSUE THREAD

**Issue by tkdeshpande** [TestStack/White#574]
Found with **_TestStack.White v0.13.3_**.

Got the following error message on running a test:
------ Run test started ------
[xUnit.net 00:00:01.0285065]   Starting:    TestStack.white
[xUnit.net 00:00:01.2396235]     TestStack.white.Tests.SingIn [FAIL]
[xUnit.net 00:00:01.2416783]       System.IO.FileLoadException : Could not load file or assembly 'TestStack.White, Version=0.13.0.0, Culture=neutral, PublicKeyToken=2672efbf3e161801' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
[xUnit.net 00:00:01.2429125]       Stack Trace:
[xUnit.net 00:00:01.2434086]            at TestStack.white.Tests.SingIn()
[xUnit.net 00:00:01.2562434]   Finished:    TestStack.white
========== Run test finished: 1 run (0:00:01.3144181) ==========

Observed the same issue on multiple machines with Visual Studio 2015 and SharpDevelop v5. 

I found that the version of the **TestStack.White.dll** is different in its properties and in the IDE.
![image](https://user-images.githubusercontent.com/6124796/30140412-f1426aa8-9391-11e7-9a9d-0412029962c5.png)

As of now I am completely blocked by this issue, so if anyone can help, it would be awesome!
Thanks!

**Comment by Roemer** [comment]
Check your assemblys binding redirects or add one. There seems to be something odd with your project setup.

**Comment by duanwalker** [comment]
i had built a client application to consume a .dll that i intended to use elsewhere and was getting this same error from System.IO.Compression . turns out the system.io.compression in the .dll was out of sync with the clients version. i just uninstalled from the .dll and installed an updated ver and it worked.
![client1](https://user-images.githubusercontent.com/7536426/53971919-d524ac80-40cb-11e9-8344-5f9710916d8e.PNG)
![dll1](https://user-images.githubusercontent.com/7536426/53971920-d524ac80-40cb-11e9-8b55-f17e7403c579.PNG)
